### ISSUE TITLE
DuckDB scalability and stability improvements

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#3349] opened 2023-10-31 03:08 UTC
In prioritized order:

- [x] Support ingesting SQL sources in smaller batches (and make batch size configurable in YAML) ([PR](https://github.com/rilldata/rill/pull/3344))
- [x] Detaching attached DBs before we reopen/close handles to prevent a memory leak + do a cherry-picked patch release
- [x] Investigate performance discrepancy with DuckDB CLI – write a Go script using `go-duckdb` with just one open connection to test the performance difference
- [x] Cap `rill_pool_size` at a number around 10, regardless of CPU count
- [x] Enable overriding memory and threads and pool size using `rill env set` (`memory_override`, `threads_override`, `pool_size_override`)
- [x] https://github.com/rilldata/rill/issues/3297 (test only in staging)
- [x] Try replicating the DuckDB memory leak C snippet on a Kubernetes pod
- [x] Prevent any concurrent writes, even "drop table if exists" (which might be called concurrently by other reconcilers)
- [x] Do an audit of major projects to check for sub-optimal / problematic configurations – check and compare slots assignments, threads/memory ratios, DB file size, `external_table_storage`, `disable_thread_limit` and `__materialize_default`
- [x] Support ingesting string columns as enum values
- [x] https://github.com/rilldata/rill/issues/3341
- [ ] #3760
- [ ] https://github.com/rilldata/rill/issues/3323 (temporarily addressed in [this PR](https://github.com/rilldata/rill/pull/3344))
- [ ] #3761

**Comment by k-anshul** [comment] 2023-11-01 10:16
> Investigate performance discrepancy with DuckDB CLI – write a Go script using go-duckdb with just one open connection to test the performance difference

There is no difference in performance when using go-duckdb single connection and rill. Both are ~10% faster than cli.

**Comment by k-anshul** [comment] 2023-11-03 08:49
> Try replicating the DuckDB memory leak C snippet on a Kubernetes pod

@begelundmuller didn't see any memory leak on k8s pod as well. Looking at the answer on go-duckdb [here](https://github.com/marcboeker/go-duckdb/issues/111#issuecomment-1707202456) specifically this part `if you leave a connection, prepared statement or appender open, the connection/prepared statement/appender will keep a reference to the database object and the database will not be destroyed.`
What I see is that as soon as I do a `RenameTable` in my script memory usage goes down (since all DBs get dettached due to `tx=true` call) however when observing this on production I don't see memory usage going down so I am suspecting we could be leaking something here(may be in some error cases). I am also reviewing driver code again.

**Comment by k-anshul** [comment] 2023-11-03 12:54
> however when observing this on production I don't see memory usage going down

Okay this could be just different behaviour(either `top` command or `duckdb`) on linux/mac. I reproduced same behaviour on duckdb cli but memory usage never crosses the limit.

**Comment by k-anshul** [comment] 2023-11-22 12:03
> Support ingesting string columns as enum values

So I deployed one project with full dataset and converted to enum.
This is definitely faster when doing side by side comparison even when running with 65 slots on new dashboard vs 85 slots on old dashboard.
So there is 100% a case for enum conversion.
But the cause of worry and blocker in rolling this out is that the refresh took 64 minutes out of which last ~45 minutes were just spent doing ALTER with temp file increasing to even 110GB.

Instead of doing ALTER we can directly write to a new db file. It ran much faster as well as reduced the db file size. 
Ran in ~14 minutes and db file size reduced from ~180GB to ~110GB.

**Comment by k-anshul** [comment] 2023-11-23 13:12
Performance numbers using k6 load-test:
On db size ~180GB, 130GB memory and 16 threads:

1. On first load (no memory mapping) enum casted data is 15% faster. It is 22% faster when instead of doing ALTER db we rewrite db file.
2. When data has been memory mapped dashboard loads in almost similar time(in fact enum casted data is slower possibly bcz of increased db size). However it is 12% faster when checking with rewritten db file(again possibly due to reduced db size).

cc : @nishantmonu51 @begelundmuller

**Comment by k-anshul** [comment] 2024-01-02 09:13
Closing and moving last three subtasks to separate issues.

**Closed by k-anshul** 2024-01-02 09:13 UTC
Labels: Area:Performance
