### ISSUE TITLE
`rill init --db <duckDbpath>` does not add DuckDB tables to the Rill catalog

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#1149] opened 2022-10-31 05:55 UTC
To reproduce w/ the AdBids dataset:
1. Download the AdBids dataset: `wget https://raw.githubusercontent.com/rilldata/rill-developer/main/web-local/test/data/AdBids.csv`
2. Start DuckDB w/ a persistent database file: `duckdb test.db`
3. Create a DuckDB table: `CREATE TABLE adbids AS SELECT * FROM read_csv_auto('AdBids.csv');`
4. Exit duckdb: `.exit`
5. Initialize Rill with the DuckDB file: `rill init --db test.db`
6. Start rill: `rill start`
7. Observe that queries to the `adbids` table work, but there are no sources listed in the assets sidebar
8. Exit Rill, open `test.db` w/ DuckDB, and see that there are no entries in `rill.catalog`

![image](https://user-images.githubusercontent.com/14206386/198939429-5553b0f4-9eac-43fa-8e41-5c674b630844.png)

**Comment by magorlick** [comment] 2022-10-31 13:12
Relates to this community report - seems like a long standing issue. https://github.com/rilldata/rill-developer/issues/153

**Comment by hamilton** [comment] 2022-10-31 15:46
@AdityaHegde says that there's some code missing in the runtime to do this, likely a small change. @magorlick should we tackle this as a P0?

**Comment by ericpgreen2** [comment] 2022-10-31 16:09
One consideration: a better long-term state would be for us to deprecate the `rill init --db <duckDbpath>` command in favor of having a dedicated DuckDB connector (as we do for S3, GCS, & local files).

**Comment by hamilton** [comment] 2022-10-31 17:29
@ericpgreen2 that seems sensible to me. In terms of workflow, people generally will be interested in bringing their whole duckdb db along for the ride, since often they have already put in just enough data to do the thing they care about. How do we make it easy for them to jump-start Rill Developer w/ a fresh set of tables?

@begelundmuller has some thinking generally around this. First step is to figure out the right conceptual model & follow it.

**Comment by magorlick** [comment] 2022-10-31 17:35
If we do take the path of a duckDB connector, I would love us to also consider how we might leverage their ability to scan postgres to get more utility. https://duckdb.org/2022/09/30/postgres-scanner.html

**Comment by ericpgreen2** [comment] 2022-10-31 17:43
@magorlick, DuckDB's Postgres scanner could be used in our implementation of a Postgres connector (which would be awesome!). But the _DuckDB_ connector will assume tables are already in DuckDB & won't use the Postgres scanner at all.

**Comment by begelundmuller** [comment] 2022-10-31 18:03
I've got functionality for discovering existing tables and adding them to the catalog (and exposing them over the catalog APIs) in a branch that I'm merging this week. That should allow us to render existing tables in the sidebar. I would argue for listing them under "sources" – maybe add a small icon or something to differentiate them.

I initially also thought we should consider existing tables as sources, but have changed my mind. On the backend, they're easier to deal with as a separate concept. On the frontend, it gives us more flexibility regarding whether to treat them similarly or differently from sources. And in the future, we might want/need to support tables in Rill (conceptually, they're slightly different than sources and models).

About Postgres, I agree we should consider it a source. We could add a "push down queries" property or something like that on the source to let the user decide whether data should be copied into DuckDB or queried through the foreign data wrapper.

**Comment by nishantmonu51** [comment] 2022-11-01 11:39
As benjamin pointed out this has more scoping work to be done than just discovering and exposing them in catalog.  
e.g. What would be the expected behavior of the refresh button for such discovered tables ? is there a refresh path at all ? 

One way is to have a slight distinction by introducing a managed and external source concept, where managed sources are managed via Rill and external sources are managed externally of Rill.

Can we get a more detailed proposal PRD spec and scoping proposal for this feature?

**Comment by hamilton** [comment] 2022-11-01 14:36
@nishantmonu51 yep I think a short proposal would be good here. Thanks for adding the label; I'll assign myself to this for now.

**Comment by ericpgreen2** [comment] 2022-11-01 16:48
If this is going to take some time, we should probably remove the DuckDB instructions from our docs.

**Comment by magorlick** [comment] 2022-11-01 17:08
This feature has been removed from out docs.

**Comment by magorlick** [comment] 2022-11-01 17:30
This issue has been removed from version 0.14. We don't have the design work together and we are already pressed for time.

**Comment by ericpgreen2** [comment] 2022-11-01 18:14
Do you want me to remove it from the CLI too?

**Comment by magorlick** [comment] 2022-11-02 13:48
@ericpgreen2 I defer to @hamilton here, but my take is that I do not think that is worth the effort to pull this code from our application because we will want to get back to this and fix it. We will always want a CLI path for existing duckDB databases just like we do for the new remote sources. If users want to try an undocumented and unsupported CLI feature for a Tech Preview of our tool I think that is ok.

**Comment by hamilton** [comment] 2022-11-02 17:29
Yeah I think it's ok to leave it in the CLI undocumented for now. As we talk through CLI design in the coming few days we will make sure to address this for `0.15` one way or another.

**Comment by hamilton** [comment] 2022-11-02 17:49
To clarify we can remove it from the CLI args but leave the code path for now until we figure this out.

**Closed** 2023-11-02 01:34 UTC
Labels: bug, needs_scoping
