### ISSUE TITLE
--readonly mode allows to edit local files

### ISSUE THREAD

**Issue by azat** [rilldata/rill#5789] opened 2024-09-26 15:50 UTC
**To Reproduce**
- run rill locally in folder with --readonly (`rill start --readonly`)
- try to edit any file - it will be modified

**Expected behavior**
The file should not be modified

**Additional context**
Here https://github.com/rilldata/rill/issues/5039#issuecomment-2242720421 @begelundmuller already wrote about the same issue I guess, but it will be nice to limit the editions even for local deployment

**Comment by begelundmuller** [comment] 2024-10-14 15:07
Hello @azat, the current `--readonly` support is designed to put the application into a state focused on presenting dashboards instead of developing them, but it is unfortunately not designed for securely locking down the application (as would for example be needed for hosting Rill on a server). For hosting, the only currently supported approach is using Rill Cloud (by running `rill deploy` from the CLI).

However thank you for sharing this feature request and we will update you if/when we support a self-hostable configuration of Rill.

**Comment by begelundmuller** [comment] 2024-10-17 10:46
I'm closing this issue since it's currently working as intended, but let me know if I misunderstood the issue and you think it should be re-opened.

**Comment by ericpgreen2** [comment] 2024-10-17 13:12
Yeah, this is a valid open issue, so I'll re-open. From the UI perspective, the `--readonly` flag should only present the "Preview" mode, not show the file editor.

**Comment by ericpgreen2** [comment] 2024-11-26 15:50
We've elected to [deprecate](https://github.com/rilldata/rill/pull/5992) the `--readonly` flag. It was a relic of Rill Developer before the launch of Rill Cloud, and clearly we haven't properly maintained it. Today, dashboards should be shared with others via Rill Cloud.

**Closed by ericpgreen2** 2024-11-26 15:50 UTC
Labels: Type:Bug
