### ISSUE TITLE
Fix: Measure filter seems to filter out extra data

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3980] opened 2024-02-06 22:10 UTC
JAM video: https://jam.dev/c/7caa6124-464b-4208-be58-295ecb67d8ec

In the video, note that filtering for "New cases" > 0, both 'Panama' (50 new cases) and 'Turks and Caicos Islands' (10 new cases) get filtered out.

Here's a public dashboard where you can observe the behavior: [COVID dashboard](https://ui.rilldata.com/ericpgreen/rill-test-covid/covid?state=CgUKA1A0VxgFKgltZWFzdXJlXzE4AEgBWAFgBGoTQW1lcmljYS9Mb3NfQW5nZWxlc3gCgAEBmAH%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F8BogEqGigICBIkGiIICRILCgljb250aW5lbnQSERIPGg1Ob3J0aCBBbWVyaWNhqgEwCghsb2NhdGlvbhIkGiIICBIeGhwIBRILCgltZWFzdXJlXzESCxIJEQAAAAAAAAAA).

**Comment by AdityaHegde** [comment] 2024-03-07 05:33
This needs backend refactor with subqueries to get the accurate support.

**Comment by nishantmonu51** [comment] 2024-04-08 19:50
Reassigning to @begelundmuller for getting prioritized on platform side.

**Comment by begelundmuller** [comment] 2024-04-09 09:28
> This needs backend refactor with subqueries to get the accurate support.

@AdityaHegde can you elaborate on what the issue is here?

**Comment by egor-ryashin** [comment] 2024-04-30 09:18
That's because `toplist` query wasn't given a filter while `compare-toplist` had it. This the response from `toplist`:
```
{
    "meta": [
        {
            "name": "domain",
            "type": "CODE_STRING",
            "nullable": true
        },
        {
            "name": "total_records",
            "type": "CODE_INT64",
            "nullable": true
        }
    ],
    "data": [
        {
            "domain": "facebook.com",
            "total_records": 15609
        },
        {
            "domain": "msn.com",
            "total_records": 15526
        },
        {
            "domain": "google.com",
            "total_records": 15119
        },
        {
            "domain": "news.yahoo.com",
            "total_records": 14870
        },
        {
            "domain": "instagram.com",
            "total_records": 13104
        },
        {
            "domain": "sports.yahoo.com",
            "total_records": 12889
        },
        {
            "domain": "news.google.com",
            "total_records": 12883
        }
    ]
}
```
This is the response from `compare-toplist`:
```
{
    "rows": [
        {
            "dimensionValue": "facebook.com",
            "measureValues": [
                {
                    "measureName": "total_records",
                    "baseValue": 10533,
                    "comparisonValue": null,
                    "deltaAbs": null,
                    "deltaRel": null
                }
            ]
        },
        {
            "dimensionValue": "google.com",
            "measureValues": [
                {
                    "measureName": "total_records",
                    "baseValue": 10119,
                    "comparisonValue": null,
                    "deltaAbs": null,
                    "deltaRel": null
                }
            ]
        },
        {
            "dimensionValue": "news.yahoo.com",
            "measureValues": [
                {
                    "measureName": "total_records",
                    "baseValue": 9982,
                    "comparisonValue": null,
                    "deltaAbs": null,
                    "deltaRel": null
                }
            ]
        },
        {
            "dimensionValue": "instagram.com",
            "measureValues": [
                {
                    "measureName": "total_records",
                    "baseValue": 8808,
                    "comparisonValue": null,
                    "deltaAbs": null,
                    "deltaRel": null
                }
            ]
        },
        {
            "dimensionValue": "news.google.com",
            "measureValues": [
                {
                    "measureName": "total_records",
                    "baseValue": 8644,
                    "comparisonValue": null,
                    "deltaAbs": null,
                    "deltaRel": null
                }
            ]
        },
        {
            "dimensionValue": "sports.yahoo.com",
            "measureValues": [
                {
                    "measureName": "total_records",
                    "baseValue": 8611,
                    "comparisonValue": null,
                    "deltaAbs": null,
                    "deltaRel": null
                }
            ]
        }
    ]
}
```
See that for the same time range the values are different - that is because `toplist` wasn't given the filter parameter and didn't filter out *nulls*.
This the request for `toplist`:
```
{
   "dimensionName":"domain",
   "measureNames":[
      "total_records"
   ],
   "having":{
      "cond":{
         "op":"OPERATION_AND",
         "exprs":[
            {
               "cond":{
                  "op":"OPERATION_GT",
                  "exprs":[
                     {
                        "ident":"total_records"
                     },
                     {
                        "val":9110
                     }
                  ]
               }
            }
         ]
      }
   },
   "timeStart":"2022-01-01T00:00:23.046Z",
   "timeEnd":"2022-03-30T23:59:43.201Z",
   "limit":"50",
   "offset":"0",
   "sort":[
      {
         "name":"total_records",
         "ascending":false
      }
   ]
}
```
This is the request for `compare-toplist`:
```
{
   "dimension":{
      "name":"domain"
   },
   "measures":[
      {
         "name":"total_records"
      }
   ],
   "comparisonMeasures":[
      
   ],
   "timeRange":{
      "start":"2022-01-01T00:00:23.046Z",
      "end":"2022-03-30T23:59:43.201Z"
   },
   "comparisonTimeRange":{
      
   },
   "sort":[
      {
         "desc":true,
         "name":"total_records",
         "sortType":"METRICS_VIEW_COMPARISON_MEASURE_TYPE_BASE_VALUE"
      }
   ],
   "where":{
      "cond":{
         "op":"OPERATION_AND",
         "exprs":[
            {
               "cond":{
                  "op":"OPERATION_IN",
                  "exprs":[
                     {
                        "ident":"publisher"
                     },
                     {
                        "val":"Facebook"
                     },
                     {
                        "val":"Google"
                     },
                     {
                        "val":"Yahoo"
                     }
                  ]
               }
            },
            {
               "cond":{
                  "op":"OPERATION_IN",
                  "exprs":[
                     {
                        "ident":"domain"
                     },
                     {
                        "val":"facebook.com"
                     },
                     {
                        "val":"msn.com"
                     },
                     {
                        "val":"google.com"
                     },
                     {
                        "val":"news.yahoo.com"
                     },
                     {
                        "val":"instagram.com"
                     },
                     {
                        "val":"sports.yahoo.com"
                     },
                     {
                        "val":"news.google.com"
                     }
                  ]
               }
            }
         ]
      }
   },
   "limit":"8",
   "offset":"0"
}
```
See that the filter wasn't specified in `toplist`.

![image](https://github.com/rilldata/rill/assets/14215045/1e890a6a-8cd4-4436-b7c6-7985149f2e88)

**Closed** 2024-05-07 20:55 UTC
Labels: Type:Bug
