### ISSUE TITLE
Pivot: sorting by a column triggers a 400 error from the Aggregation API

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4573] opened 2024-04-10 17:19 UTC
I've tried to sort by FuboTV Requests:
![image](https://github.com/rilldata/rill/assets/14206386/aeaa27cc-5c27-4d33-bdf9-a4c1b586dfc8)

Here's the error from the Aggregation API:
```
{
    "code": 2,
    "message": "Binder Error: Values list \"auction_data_model\" does not have a column named \"__time\"",
    "details": []
}
```

Link: https://ui.rilldata.com/demo/rill-openrtb-prog-ads/auction?state=CgUKA1AxVxgFKghyZXF1ZXN0czgASAFYAWAEagdFdGMvVVRDeAKAAQGYAf%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252FwGiAQQaAggIsAEBugEBBMIBD2FwcF9zaXRlX2RvbWFpbtIBDWFwcF9zaXRlX25hbWXaAQhyZXF1ZXN0c%252BoBCggBEgZjMHYybTDwAQH4AQKAAgQ%253D

**Comment by mindspank** [comment] 2024-04-17 17:14
Can't reproduce in the same dash with a fresh state proto.

**Comment by ericpgreen2** [comment] 2024-04-17 17:45
I just tried to reproduce and now I'm getting slightly different buggy behavior. Sorting by a column causes the table to disappear entirely. JAM: https://jam.dev/c/52b0109d-9f1e-4608-be4c-fe6fa99e5964

**Comment by djbarnwal** [comment] 2024-04-17 18:01
Looks like a bug with the API. @egor-ryashin can you take a look? The request and response is available in the jam link above.

**Comment by egor-ryashin** [comment] 2024-04-19 12:50
Thanks https://github.com/rilldata/rill/pull/4667

**Comment by begelundmuller** [comment] 2024-04-29 15:43
Closed by https://github.com/rilldata/rill/pull/4667

**Closed by begelundmuller** 2024-04-29 15:43 UTC
Labels: Type:Bug, Area:Pivot
